# Pipeline summary.
# This is triggered both by pull requests and by merges to master branch.
# Some of the stages/jobs/scripts below are conditionally ran depending on how the pipeline was triggered.
resources:
  repositories:
    - repository: qa-automation
      type: github
      name: git-template-repo-name/templates
      endpoint: ghe

trigger:

pr:

variables:
  - group: automation-secret
  - group: Defaults
  - name: System.Debug
    value: true

parameters:
  - name: myenv
    type: string
    default: $(stack)


stages:
  - template: templates/promotion-v2.yaml
    parameters:
      service: $(service)
      stack: $(stack)
      tag: $(tag)
      repository: $(repository)
      skipTests: false
      dockerRegistryConnection: harbor
      harborRegistryHost: $(HarborRegistryHost)
      disableConcurrentBuilds: true

      systemTestList:
        - language: java
          testParams:
            testArtifacts:
              - 'cucumber/results/*'
              - 'cucumber/logs/*'
            testArgsMap:
              dev: test -Dgroups=IntegrationTest -Dapitest.controller.filename=Promotion_Pipeline_Controller.jmx -Denv=dev -DsolacePassword=$(SOLACEPASSWORD) -DfullAccessClient_Secret=$(fullAccessClient_Secret_ITG)
              itg: test -Dgroups=IntegrationTest -Dapitest.controller.filename=Promotion_Pipeline_Controller.jmx -Denv=itg -DsolacePassword=$(SOLACEPASSWORD) -DfullAccessClient_Secret=$(fullAccessClient_Secret_ITG)
              stg: test -Dgroups=IntegrationTest -Dapitest.controller.filename=Promotion_Pipeline_Controller.jmx -Denv=stg-us -DsolacePassword=$(SOLACEPASSWORD) -DfullAccessClient_Secret=$(fullAccessClient_Secret_STG)
            useProxy: false
