trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  name: 'MyAgentPool'
steps:
  - script: |
      echo "Running on self-hosted agent"
      npm install
      mkdir -p reports/cucumber
      npm run test:integration
    displayName: 'Run Tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: reports/cucumber/cucumber-report.json
      artifact: cucumber-report
    displayName: 'Upload Report'
