name: Check PR for Cucumber Test Cases

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install @octokit/rest
      - name: Check for Cucumber test cases
        env:
          GITHUB_TOKEN: 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
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node check_tests.js
