name: Check PR for Cucumber Test Cases

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Check for Cucumber test cases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node check_tests.js
